### ISSUE TITLE
user_cas + OC 8.0.6 + user_ldap exception

### ISSUE THREAD

**Issue by timm2k** [owncloud/user_cas#16]
Hi,

when I try to enable function "Link CAS authentication with LDAP users and groups backend" I get following exception after loggin in via cas:

`{"reqId":"7ebda43fa0c073e139cee9f781bac2bf","remoteAddr":"134.106.68.78","app":"index","message":"Exception: {\"Message\":\"UserMapper was not assigned to this Access instance.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/access.php(364): OCA\\\\user_ldap\\\\lib\\\\Access->getUserMapper()\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/access.php(352): OCA\\\\user_ldap\\\\lib\\\\Access->dn2ocname('uid=user1,ou...', NULL, true)\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/user_cas\\\/lib\\\/ldap_backend_adapter.php(122): OCA\\\\user_ldap\\\\lib\\\\Access->dn2username('uid=user1,ou...')\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/user_cas\\\/user_cas.php(127): OCA\\\\user_cas\\\\lib\\\\LdapBackendAdapter->getUuid('user1')\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/user\\\/manager.php(159): OC_USER_CAS->checkPassword('', '')\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/user\\\/session.php(196): OC\\\\User\\\\Manager->checkPassword('', '')\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/user.php(216): OC\\\\User\\\\Session->login('', '')\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/user_cas\\\/appinfo\\\/app.php(50): OC_User::login('', '')\\n#8 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/app.php(117): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#9 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/app.php(98): OC_App::requireAppFile('user_cas')\\n#10 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/app.php(77): OC_App::loadApp('user_cas')\\n#11 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/user.php(149): OC_App::loadApps(Array)\\n#12 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/base.php(607): OC_User::setupBackends()\\n#13 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/base.php(1039): OC::init()\\n#14 \\\/var\\\/www\\\/html\\\/owncloud\\\/index.php(34): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#15 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/user_ldap\\\/lib\\\/access.php\",\"Line\":85}","level":4,"time":"2015-08-14T10:45:18+02:00","method":"GET","url":"\/"}` 

Is there a solution?

ownCloud 8.0.6
PHP 5.4
phpCAS 1.3.3

Regards
Timm

**Comment by timeos** [comment]
yes, please have a look on pull requests -> Owncloud > 8.0.2 compatibilty fixes -> "Fix ldap_backend_adapter initialization to be compatible with Owncloud". Update your "lib/ldap_backend_adapter.php" accordingly as this request wasnt yet accepted.

**Comment by timm2k** [comment]
timeos thanks for your quick reply.

I can confirm that the fix is working.
Meanwhile the pull request has been processed.
