### ISSUE TITLE
an error occured in updating to ownCloud 8.2.0

### ISSUE THREAD

**Issue by papillon326** [owncloud/user_cas#22]
I try to update from ownCloud 8.1.0.
>$ sudo -u apache /usr/bin/php occ upgrade
>Checked database schema update for apps
>...
>Updating <user_cas> ...
>Updated <user_cas> to 1.1
>PHP Fatal error:  Class 'OC_Log' not found in /var/www/owncloud-8.2.0/apps/user_cas/user_cas.php on line 76

I thnk use "\OCP\Util::writeLog()" instead of "OC_Log::write()".

**Comment by nitmir** [comment]
I am facing the same issue
