### ISSUE TITLE
PHP Fatal error:  Call to undefined method OC_Util::generateRandomBytes()

### ISSUE THREAD

**Issue by c0r3dump3d** [owncloud/user_cas#31]
Hi, I'm trying to install the cas auth plugin in owncloud 9 but I have this error after authentication is successful:

PHP Fatal error:  Call to undefined method OC_Util::generateRandomBytes() in /var/www/html/owncloud/apps/user_cas/lib/hooks.php on line 73

**Comment by bastienho** [comment]
Hi @c0r3dump3d,

I have the sale issue, could you please tell us how you solved it?

thank you
