### ISSUE TITLE
Installation user_cas

### ISSUE THREAD

**Issue by isnoor** [owncloud/user_cas#47]
I am trying install user_cas with phpcas 1.3.5. I have problem on the process "Access the administration panel and configure the CAS app". While I push click and post form to "http://...//owncloud/index.php/settings/admin?sectionid=additional#", give return "405 Method Not Allowed"

**Comment by felixrupp** [comment]
Hello @isnoor 

Please provide more information on what ownCloud, PHP and user_cas version you are using. 

Please answer these questions:
- What led up to the situation?
- What exactly did you do (or not do) that was effective (or ineffective)?
- What was the outcome of this action?
- What outcome did you expect instead?

Also please provide basic information of your Owncloud instance:
- Owncloud Version
- PHP Version
- CAS Version
- phpcas library version
- The part of the owncloud.log file, from -5min. before and +5min. after the bug happened

Regards,
Felix

**Comment by isnoor** [comment]
Hai @felixrupp 
Thanks for your response. 
I have deal with that problem. Now, we used PHP 7.0, Owncloud 10.0.8 and user-cas 1.4.9. 
We modify some code.

Regards,
Isnoor

**Comment by felixrupp** [comment]
Hi @isnoor 
for ownCloud 10.0.8 you should use 1.5.4, as there is a major code change in ownCloud 10.0.8 which breaks the User Backend of the app.

Regards
Felix

**Comment by isnoor** [comment]
Thanks @felixrupp
